export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "primary-fixed-dim": "#bec6e0",
          "surface-bright": "#f7f9fb",
          "error-container": "#ffdad6",
          "secondary": "#505f76",
          "surface-dim": "#d8dadc",
          "on-tertiary-fixed-variant": "#004395",
          "primary": "#000000",
          "error": "#ba1a1a",
          "on-primary-fixed-variant": "#3f465c",
          "on-error-container": "#93000a",
          "inverse-surface": "#2d3133",
          "on-surface": "#191c1e",
          "tertiary-container": "#001a42",
          "background": "#f7f9fb",
          "inverse-primary": "#bec6e0",
          "inverse-on-surface": "#eff1f3",
          "primary-fixed": "#dae2fd",
          "surface-container-low": "#f2f4f6",
          "surface-container-highest": "#e0e3e5",
          "on-primary": "#ffffff",
          "on-secondary-fixed": "#0b1c30",
          "outline-variant": "#c6c6cd",
          "on-secondary-fixed-variant": "#38485d",
          "on-secondary": "#ffffff",
          "on-error": "#ffffff",
          "on-surface-variant": "#45464d",
          "surface-container-high": "#e6e8ea",
          "secondary-container": "#d0e1fb",
          "outline": "#76777d",
          "secondary-fixed": "#d3e4fe",
          "surface-container": "#eceef0",
          "on-tertiary-container": "#3980f4",
          "secondary-fixed-dim": "#b7c8e1",
          "tertiary-fixed": "#d8e2ff",
          "on-tertiary": "#ffffff",
          "surface": "#f7f9fb",
          "surface-tint": "#565e74",
          "surface-container-lowest": "#ffffff",
          "tertiary-fixed-dim": "#adc6ff",
          "on-background": "#191c1e",
          "on-primary-container": "#7c839b",
          "tertiary": "#000000",
          "surface-variant": "#e0e3e5",
          "on-tertiary-fixed": "#001a42",
          "on-secondary-container": "#54647a",
          "primary-container": "#131b2e",
          "on-primary-fixed": "#131b2e"
      }
    }
  }
}
